### ISSUE TITLE
error

### ISSUE THREAD

**Issue by nmds9** [SakaraCheggit/AI_Measurements#1] opened 2021-07-01 13:38 UTC
![捕获123](https://user-images.githubusercontent.com/49751897/124133712-af99e900-dab4-11eb-9f35-acd0e51aba2d.PNG)

**Comment by SakaraCheggit** [comment] 2021-07-08 21:26
Can you check Discord? I sent you a DM with some more information I'll need in order to troubleshoot this.

**Comment by sunxyw** [comment] 2021-07-09 09:57
Same issue here, any solution?

**Comment by sunxyw** [comment] 2021-07-10 08:03
Here is how I solved this:

Please update your BepInEx and HS2API / AIAPI to the latest version.
You can find latest BepInEx release [here](https://github.com/BepInEx/BepInEx/releases), and HS2API / AIAPI [here](https://github.com/IllusionMods/IllusionModdingAPI/releases).

Hope this can help you.

**Comment by SakaraCheggit** [comment] 2021-07-13 15:35
Issue is caused by having an outdated version of BepInEx. The latest version ([1.1.0](https://github.com/SakaraCheggit/AI_Measurements/releases/tag/1.1.0)) is compiled against BepInEx 5.4.8. Later versions can be found on [BepInEx's release page](https://github.com/BepInEx/BepInEx/releases).

Closing issue as resolved.

**Closed as completed by SakaraCheggit** 2021-07-13 15:35 UTC
